import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class LanguageService {
  private currentLang = 'en';

  private translations: { [lang: string]: { [key: string]: string } } = {
    en: {
      bus_tickets: 'Bus Tickets',
      cab_rental: 'Cab Rental',
      train_tickets: 'Train Tickets',
      community: 'Community',
      route_planner: 'Route Planner',
      help: 'Help',
      account: 'Account',
      my_profile: 'My Profile',
      my_trips: 'My Trips',
      sign_out: 'Sign Out',
      login_signup: 'Login / SignUp',
      hero_title: "India's No. 1 Online Bus Ticket Booking Site",
      from: 'From',
      to: 'To',
      date: 'Date',
      search_buses: 'SEARCH BUSES',
      search_cabs: 'SEARCH CABS',
      search_trains: 'SEARCH TRAINS',
      trending_offers: 'TRENDING OFFERS',
      view_all: 'View All',
      faq_title: 'FREQUENTLY ASKED QUESTIONS',
      general: 'General',
      ticket_related: 'Ticket-related',
      payment: 'Payment',
      cancellation_refund: 'Cancellation & Refund',
      insurance: 'Insurance',
      all_categories: 'All Categories',
      stories_tab: 'Journey Stories',
      forums_tab: 'Discussion Boards',
      write_tab: 'Share Your Story',
      publish_story: 'Publish Story',
      verification_required: 'Verification Required',
      instant_verify: 'Instantly Get Gold Verified',
      likes: 'Likes',
      comments: 'Comments',
      share: 'Share',
      report: 'Report',
      cabs_title: 'Premium Cab Rentals',
      outstation: 'Outstation',
      airport_transfer: 'Airport Transfer',
      hourly_rental: 'Hourly Rental',
      select_vehicle: 'Select Vehicle Type',
      book_now: 'Book Now',
      trains_title: 'Express Train Tickets',
      coach_class: 'Select Coach Class',
      berth_pref: 'Berth Preference',
      irctc_verify: 'Verify IRCTC Username',
      route_planner_title: 'Interactive Route Planner',
      waypoint: 'Add Waypoint',
      alternate_route: 'Alternative Route Suggestions',
      compare_routes: 'Compare Route Options',
      save_route: 'Save Route',
      distance: 'Distance',
      travel_time: 'Travel Time',
      traffic_congestion: 'Traffic Congestion',
      rate_review: 'Rate & Review Route',
      overall_rating: 'Overall Route Rating',
      cleanliness: 'Cleanliness',
      safety: 'Safety',
      comfort: 'Comfort',
      submit_review: 'Submit Review',
      review_success: 'Review published successfully!',
      min_char_limit: 'Minimum character limit not met.',
      trusted_reviewer: 'Trusted Reviewer',

      // Added keys for comprehensive search results translation
      filters: 'Filters',
      departure_time: 'DEPARTURE TIME',
      bus_types: 'BUS TYPES',
      arrival_time: 'ARRIVAL TIME',
      amenities: 'AMENITIES',
      live_tracking: 'Live Tracking',
      reschedulable: 'Reschedulable',
      safety_factor_msg: 'All bus ratings include safety as a major factor',
      buses_list: 'BUSES LIST',
      sort_by: 'SORT BY :',
      departure: 'Departure',
      duration: 'Duration',
      arrivals: 'Arrivals',
      ratings: 'Ratings',
      fare: 'Fare',
      seats_available: 'Seats Available',

      // Seat & Booking
      boarding_dropping: 'Boarding and Dropping',
      change: 'Change',
      departure_loc: 'Departure Location',
      arrival_loc: 'Arrival Location',
      seat_no: 'Seat No.',
      fare_details: 'Fare Details',
      amount: 'Amount',
      taxes_msg: 'Taxes will be calculated during Payment',
      proceed_to_book: 'Proceed To Book',
      enter_passenger_details: 'Enter Passenger Details',
      passenger_info: 'Passenger Information',
      passenger: 'Passenger',
      seat: 'Seat',
      name: 'Name',
      gender: 'Gender',
      male: 'Male',
      female: 'Female',
      age: 'Age',
      contact_details: 'Contact Details',
      ticket_sent_msg: 'Your ticket will be sent to these details',
      email: 'Email',
      phone: 'Phone',
      business_travel_msg: 'I am booking tickets for business travel.',
      whatsapp_updates_msg: 'Send updates and booking details on my Whatsapp number.',
      insurance_msg: 'Insure your travel by adding Rs 15 per passenger. Powered by ICICI Lombard GIC Ltd',
      loss_of_baggage: 'Loss of baggage',
      baggage_cover: 'Upto Rs. 3000 insurance cover',
      personal_accident: 'Personal Accident',
      accident_cover: 'Rs. 6,00,000 insurance cover',
      secure_trip_checkbox: 'Yes, secure my trip with insurance, I have read and understood the Terms and conditions',
      covid_donation: 'COVID Donation',
      terms_agreement_msg: 'By clicking on proceed, I agree that I have read and understood the TnCs and the Privacy Policy',
      proceed_to_pay: 'proceed to pay',

      // Payment Details
      enter_offer_code: 'ENTER OFFER CODE',
      safe_secure: 'Safe and Secure',
      online_payments: 'Online Payments',
      million_trans: '60+ million',
      transactions: 'transactions',
      years_trust: '10+ years of',
      trust: 'Trust',
      pay_with_stripe: 'Pay With Stripe',
      choose_other_payment: 'Choose Other Payment Method',
      credit_card: 'Credit Card',
      debit_card: 'Debit Card',
      wallets: 'Wallets',
      net_banking: 'Net Banking',
      upi_payment_msg: 'UPI PAYMENT USING PHONEPAY / GPAY / AMAZONPAY ETC...',
      pay_qr: 'Pay through QR Code',
      pay_upi_id: 'Pay through UPI ID',
      new_label: 'New',
      trip_details: 'Trip Details',
      booking_date: 'Booking Date',
      seats_booked: 'Seats Booked',
      boarding_point: 'Boarding Point',
      dropping_point: 'Dropping Point',
      fare_breakup: 'FARE BREAKUP',
      total_payable: 'Total Payable',

      // Authentication
      login_title: 'Sign in to your account',
      create_account_prompt: "Don't have an account?",
      sign_up_here: 'Sign up here',
      email_address: 'Email Address',
      password: 'Password',
      forgot_password: 'Forgot password?',
      sign_in: 'Sign In',
      signing_in: 'Signing in...',
      create_account_title: 'Create your account',
      already_have_account: 'Already have an account?',
      sign_in_here: 'Sign in here',
      first_name: 'First Name',
      last_name: 'Last Name',
      phone_number: 'Phone Number (10 digits)',
      date_of_birth: 'Date of Birth',
      create_account: 'Create Account',
      creating_account: 'Creating account...',
      forgot_password_title: 'Forgot Password',
      forgot_password_desc: 'Enter your email address and we will send you a reset link.',
      send_reset_link: 'Send Reset Link',
      sending: 'Sending...',
      back_to_login: 'Back to Login',
      reset_password_title: 'Reset your password',
      new_password: 'New Password',
      confirm_password: 'Confirm Password',
      reset_password: 'Reset Password',
      resetting: 'Resetting...'
    },
    hi: {
      bus_tickets: 'बस टिकट',
      cab_rental: 'कैब बुकिंग',
      train_tickets: 'ट्रेन टिकट',
      community: 'कम्युनिटी',
      route_planner: 'रूट प्लानर',
      help: 'सहायता',
      account: 'खाता',
      my_profile: 'मेरी प्रोफाइल',
      my_trips: 'मेरी यात्राएं',
      sign_out: 'साइन आउट',
      login_signup: 'लॉगिन / साइनअप',
      hero_title: 'भारत की नंबर 1 ऑनलाइन बस टिकट बुकिंग साइट',
      from: 'कहाँ से',
      to: 'कहाँ तक',
      date: 'दिनांक',
      search_buses: 'बसें खोजें',
      search_cabs: 'कैब खोजें',
      search_trains: 'ट्रेनें खोजें',
      trending_offers: 'प्रचलित ऑफर्स',
      view_all: 'सभी देखें',
      faq_title: 'अक्सर पूछे जाने वाले प्रश्न',
      general: 'सामान्य',
      ticket_related: 'टिकट संबंधी',
      payment: 'भुगतान',
      cancellation_refund: 'रद्द करना और वापसी',
      insurance: 'बीमा',
      all_categories: 'सभी श्रेणियां',
      stories_tab: 'यात्रा की कहानियां',
      forums_tab: 'चर्चा मंच',
      write_tab: 'अपनी कहानी साझा करें',
      publish_story: 'कहानी प्रकाशित करें',
      verification_required: 'सत्यापन आवश्यक',
      instant_verify: 'तुरंत गोल्ड सत्यापित प्राप्त करें',
      likes: 'पसंद',
      comments: 'टिप्पणियाँ',
      share: 'साझा करें',
      report: 'रिपोर्ट करें',
      cabs_title: 'प्रीमियम कैब रेंटल',
      outstation: 'बाहरी स्टेशन',
      airport_transfer: 'हवाई अड्डा स्थानांतरण',
      hourly_rental: 'प्रति घंटा किराया',
      select_vehicle: 'वाहन का प्रकार चुनें',
      book_now: 'अभी बुक करें',
      trains_title: 'एक्सप्रेस ट्रेन टिकट',
      coach_class: 'कोच क्लास चुनें',
      berth_pref: 'बर्थ प्राथमिकता',
      irctc_verify: 'आईआरसीटीसी उपयोगकर्ता नाम सत्यापित करें',
      route_planner_title: 'इंटरैक्टिव रूट प्लानर',
      waypoint: 'रास्ता बिंदु जोड़ें',
      alternate_route: 'वैकल्पिक मार्ग सुझाव',
      compare_routes: 'मार्ग विकल्पों की तुलना करें',
      save_route: 'मार्ग सहेजें',
      distance: 'दूरी',
      travel_time: 'यात्रा समय',
      traffic_congestion: 'ट्रैफिक जाम की स्थिति',
      rate_review: 'रूट को रेट और समीक्षा करें',
      overall_rating: 'समग्र मार्ग रेटिंग',
      cleanliness: 'सफाई',
      safety: 'सुरक्षा',
      comfort: 'सुविधा',
      submit_review: 'समीक्षा जमा करें',
      review_success: 'समीक्षा सफलतापूर्वक प्रकाशित हुई!',
      min_char_limit: 'न्यूनतम वर्ण सीमा पूरी नहीं हुई।',
      trusted_reviewer: 'विश्वसनीय समीक्षक',

      // Added keys for comprehensive search results translation
      filters: 'फ़िल्टर',
      departure_time: 'प्रस्थान समय',
      bus_types: 'बस के प्रकार',
      arrival_time: 'आगमन समय',
      amenities: 'सुविधाएं',
      live_tracking: 'लाइव ट्रैकिंग',
      reschedulable: 'पुनर्निर्धारित करने योग्य',
      safety_factor_msg: 'सभी बस रेटिंग में सुरक्षा एक मुख्य कारक के रूप में शामिल है',
      buses_list: 'बसों की सूची',
      sort_by: 'इसके द्वारा क्रमबद्ध करें :',
      departure: 'प्रस्थान',
      duration: 'अवधि',
      arrivals: 'आगमन',
      ratings: 'रेटिंग',
      fare: 'किराया',
      seats_available: 'सीटें उपलब्ध',

      // Seat & Booking
      boarding_dropping: 'बोर्डिंग और ड्रॉपिंग',
      change: 'बदलें',
      departure_loc: 'प्रस्थान स्थान',
      arrival_loc: 'आगमन स्थान',
      seat_no: 'सीट संख्या',
      fare_details: 'किराये का विवरण',
      amount: 'राशि',
      taxes_msg: 'भुगतान के दौरान करों की गणना की जाएगी',
      proceed_to_book: 'बुक करने के लिए आगे बढ़ें',
      enter_passenger_details: 'यात्री विवरण दर्ज करें',
      passenger_info: 'यात्री जानकारी',
      passenger: 'यात्री',
      seat: 'सीट',
      name: 'नाम',
      gender: 'लिंग',
      male: 'पुरुष',
      female: 'महिला',
      age: 'आयु',
      contact_details: 'संपर्क विवरण',
      ticket_sent_msg: 'आपका टिकट इन विवरणों पर भेजा जाएगा',
      email: 'ईमेल',
      phone: 'फोन',
      business_travel_msg: 'मैं व्यावसायिक यात्रा के लिए टिकट बुक कर रहा हूँ।',
      whatsapp_updates_msg: 'मेरे व्हाट्सएप नंबर पर अपडेट और बुकिंग विवरण भेजें।',
      insurance_msg: 'प्रति यात्री 15 रुपये जोड़कर अपनी यात्रा का बीमा करें। आईसीआईसीआई लोम्बार्ड जीआईसी लिमिटेड द्वारा संचालित',
      loss_of_baggage: 'सामान का नुकसान',
      baggage_cover: '3000 रुपये तक का बीमा कवर',
      personal_accident: 'व्यक्तिगत दुर्घटना',
      accident_cover: '6,00,000 रुपये का बीमा कवर',
      secure_trip_checkbox: 'हाँ, मेरी यात्रा को बीमा से सुरक्षित करें, मैंने नियम और शर्तें पढ़ और समझ ली हैं',
      covid_donation: 'कोविड दान',
      terms_agreement_msg: 'आगे बढ़ने पर क्लिक करके, मैं सहमत हूँ कि मैंने नियम व शर्तें और गोपनीयता नीति पढ़ और समझ ली हैं',
      proceed_to_pay: 'भुगतान के लिए आगे बढ़ें',

      // Payment Details
      enter_offer_code: 'ऑफर कोड दर्ज करें',
      safe_secure: 'सुरक्षित और संरक्षित',
      online_payments: 'ऑनलाइन भुगतान',
      million_trans: '60+ मिलियन',
      transactions: 'लेनदेन',
      years_trust: '10+ वर्षों का',
      trust: 'विश्वास',
      pay_with_stripe: 'स्ट्राइप के साथ भुगतान करें',
      choose_other_payment: 'अन्य भुगतान विधि चुनें',
      credit_card: 'क्रेडिट कार्ड',
      debit_card: 'डेबिट कार्ड',
      wallets: 'वॉलेट्स',
      net_banking: 'नेट बैंकिंग',
      upi_payment_msg: 'फोनपे / जीपे / अमेज़नपे आदि का उपयोग करके यूपीआई भुगतान...',
      pay_qr: 'क्यूआर कोड के माध्यम से भुगतान करें',
      pay_upi_id: 'यूपीआई आईडी के माध्यम से भुगतान करें',
      new_label: 'नया',
      trip_details: 'यात्रा विवरण',
      booking_date: 'बुकिंग तिथि',
      seats_booked: 'बुक की गई सीटें',
      boarding_point: 'बोर्डिंग प्वाइंट',
      dropping_point: 'ड्रॉपिंग प्वाइंट',
      fare_breakup: 'किराये का विवरण',
      total_payable: 'कुल देय राशि',

      // Authentication
      login_title: 'अपने खाते में साइन इन करें',
      create_account_prompt: 'क्या आपका खाता नहीं है?',
      sign_up_here: 'यहाँ साइन अप करें',
      email_address: 'ईमेल पता',
      password: 'पासवर्ड',
      forgot_password: 'पासवर्ड भूल गए?',
      sign_in: 'साइन इन करें',
      signing_in: 'साइन इन हो रहा है...',
      create_account_title: 'अपना खाता बनाएं',
      already_have_account: 'पहले से ही एक खाता है?',
      sign_in_here: 'यहाँ साइन इन करें',
      first_name: 'पहला नाम',
      last_name: 'अंतिम नाम',
      phone_number: 'फ़ोन नंबर (10 अंक)',
      date_of_birth: 'जन्म तिथि',
      create_account: 'खाता बनाएं',
      creating_account: 'खाता बनाया जा रहा है...',
      forgot_password_title: 'पासवर्ड भूल गए',
      forgot_password_desc: 'अपना ईमेल पता दर्ज करें और हम आपको एक रीसेट लिंक भेजेंगे।',
      send_reset_link: 'रीसेट लिंक भेजें',
      sending: 'भेजा जा रहा है...',
      back_to_login: 'लॉगिन पर वापस जाएं',
      reset_password_title: 'अपना पासवर्ड रीसेट करें',
      new_password: 'नया पासवर्ड',
      confirm_password: 'पासवर्ड की पुष्टि करें',
      reset_password: 'पासवर्ड रीसेट करें',
      resetting: 'रीसेट हो रहा है...'
    },
    es: {
      bus_tickets: 'Billetes de Autobús',
      cab_rental: 'Alquiler de Taxis',
      train_tickets: 'Billetes de Tren',
      community: 'Comunidad',
      route_planner: 'Planificador de Rutas',
      help: 'Ayuda',
      account: 'Cuenta',
      my_profile: 'Mi Perfil',
      my_trips: 'Mis Viajes',
      sign_out: 'Cerrar Sesión',
      login_signup: 'Iniciar Sesión / Registro',
      hero_title: 'El sitio número 1 de reserva de billetes de autobús en India',
      from: 'Desde',
      to: 'Hacia',
      date: 'Fecha',
      search_buses: 'BUSCAR AUTOBUSES',
      search_cabs: 'BUSCAR TAXIS',
      search_trains: 'BUSCAR TRENES',
      trending_offers: 'OFERTAS TRENDING',
      view_all: 'Ver Todo',
      faq_title: 'PREGUNTAS FRECUENTES',
      general: 'General',
      ticket_related: 'Sobre Billetes',
      payment: 'Pago',
      cancellation_refund: 'Cancelaciones y Reembolso',
      insurance: 'Seguro',
      all_categories: 'Todas las Categorías',
      stories_tab: 'Historias de Viaje',
      forums_tab: 'Tableros de Discusión',
      write_tab: 'Comparte tu Historia',
      publish_story: 'Publicar Historia',
      verification_required: 'Verificación Requerida',
      instant_verify: 'Verificarse al Instante en Oro',
      likes: 'Me Gusta',
      comments: 'Comentarios',
      share: 'Compartir',
      report: 'Reportar',
      cabs_title: 'Alquiler de Taxis Premium',
      outstation: 'Viaje Largo',
      airport_transfer: 'Traslado al Aeropuerto',
      hourly_rental: 'Alquiler por Horas',
      select_vehicle: 'Seleccionar Tipo de Vehículo',
      book_now: 'Reservar Ahora',
      trains_title: 'Billetes de Tren Express',
      coach_class: 'Seleccionar Clase de Vagón',
      berth_pref: 'Preferencia de Litera',
      irctc_verify: 'Verificar Usuario IRCTC',
      route_planner_title: 'Planificador de Rutas Interactivo',
      waypoint: 'Añadir Punto de Ruta',
      alternate_route: 'Sugerencias de Rutas Alternativas',
      compare_routes: 'Comparar Opciones de Rutas',
      save_route: 'Guardar Ruta',
      distance: 'Distancia',
      travel_time: 'Tiempo de Viaje',
      traffic_congestion: 'Congestión de Tráfico',
      rate_review: 'Calificar y Evaluar Ruta',
      overall_rating: 'Calificación General de Ruta',
      cleanliness: 'Limpieza',
      safety: 'Seguridad',
      comfort: 'Comodidad',
      submit_review: 'Enviar Evaluación',
      review_success: '¡Evaluación publicada con éxito!',
      min_char_limit: 'Límite de caracteres mínimo no alcanzado.',
      trusted_reviewer: 'Evaluador Confiable',

      // Added keys for comprehensive search results translation
      filters: 'Filtros',
      departure_time: 'HORA DE SALIDA',
      bus_types: 'TIPOS DE AUTOBÚS',
      arrival_time: 'HORA DE LLEGADA',
      amenities: 'SERVICIOS',
      live_tracking: 'Seguimiento en Vivo',
      reschedulable: 'Reprogramable',
      safety_factor_msg: 'Todas las calificaciones de autobuses incluyen la seguridad como un factor principal',
      buses_list: 'LISTA DE AUTOBÚSES',
      sort_by: 'ORDENAR POR :',
      departure: 'Salida',
      duration: 'Duración',
      arrivals: 'Llegadas',
      ratings: 'Calificaciones',
      fare: 'Tarifa',
      seats_available: 'Asientos Disponibles',

      // Seat & Booking
      boarding_dropping: 'Embarque y Descenso',
      change: 'Cambiar',
      departure_loc: 'Lugar de Salida',
      arrival_loc: 'Lugar de Llegada',
      seat_no: 'No. de Asiento',
      fare_details: 'Detalles de Tarifa',
      amount: 'Total',
      taxes_msg: 'Los impuestos se calcularán durante el pago',
      proceed_to_book: 'Proceder a Reservar',
      enter_passenger_details: 'Ingrese los Detalles del Pasajero',
      passenger_info: 'Información del Pasajero',
      passenger: 'Pasajero',
      seat: 'Asiento',
      name: 'Nombre',
      gender: 'Género',
      male: 'Masculino',
      female: 'Femenino',
      age: 'Edad',
      contact_details: 'Detalles de Contacto',
      ticket_sent_msg: 'Su boleto se enviará a estos detalles',
      email: 'Correo electrónico',
      phone: 'Teléfono',
      business_travel_msg: 'Estoy reservando boletos para viajes de negocios.',
      whatsapp_updates_msg: 'Enviar actualizaciones y detalles de la reserva a mi número de Whatsapp.',
      insurance_msg: 'Asegure su viaje agregando Rs 15 por pasajero. Desarrollado por ICICI Lombard GIC Ltd',
      loss_of_baggage: 'Pérdida de equipaje',
      baggage_cover: 'Hasta Rs. 3000 de cobertura de seguro',
      personal_accident: 'Accidente Personal',
      accident_cover: 'Rs. 6,00,000 de cobertura de seguro',
      secure_trip_checkbox: 'Sí, asegurar mi viaje con seguro, he leído y comprendido los Términos y condiciones',
      covid_donation: 'Donación COVID',
      terms_agreement_msg: 'Al hacer clic en proceder, acepto que he leído y entendido los Términos y condiciones y la Política de privacidad',
      proceed_to_pay: 'proceder a pagar',

      // Payment Details
      enter_offer_code: 'INGRESAR CÓDIGO DE OFERTA',
      safe_secure: 'Seguro y Protegido',
      online_payments: 'Pagos en Línea',
      million_trans: '60+ millones',
      transactions: 'transacciones',
      years_trust: '10+ años de',
      trust: 'Confianza',
      pay_with_stripe: 'Pagar con Stripe',
      choose_other_payment: 'Elegir Otro Método de Pago',
      credit_card: 'Tarjeta de Crédito',
      debit_card: 'Tarjeta de Débito',
      wallets: 'Billeteras',
      net_banking: 'Net Banking',
      upi_payment_msg: 'PAGO UPI USANDO PHONEPE / GPAY / AMAZONPAY ETC...',
      pay_qr: 'Pagar mediante código QR',
      pay_upi_id: 'Pagar mediante ID de UPI',
      new_label: 'Nuevo',
      trip_details: 'Detalles del Viaje',
      booking_date: 'Fecha de Reserva',
      seats_booked: 'Asientos Reservados',
      boarding_point: 'Punto de Embarque',
      dropping_point: 'Punto de Descenso',
      fare_breakup: 'DESGLOSE DE TARIFA',
      total_payable: 'Total a Pagar',

      // Authentication
      login_title: 'Inicie sesión en su cuenta',
      create_account_prompt: '¿No tiene una cuenta?',
      sign_up_here: 'Regístrese aquí',
      email_address: 'Correo Electrónico',
      password: 'Contraseña',
      forgot_password: '¿Olvidó su contraseña?',
      sign_in: 'Iniciar Sesión',
      signing_in: 'Iniciando sesión...',
      create_account_title: 'Cree su cuenta',
      already_have_account: '¿Ya tiene una cuenta?',
      sign_in_here: 'Inicie sesión aquí',
      first_name: 'Primer Nombre',
      last_name: 'Apellido',
      phone_number: 'Teléfono (10 dígitos)',
      date_of_birth: 'Fecha de Nacimiento',
      create_account: 'Crear Cuenta',
      creating_account: 'Creando cuenta...',
      forgot_password_title: 'Contraseña Olvidada',
      forgot_password_desc: 'Ingrese su correo electrónico y le enviaremos un enlace de restablecimiento.',
      send_reset_link: 'Enviar Enlace de Restablecimiento',
      sending: 'Enviando...',
      back_to_login: 'Volver al Inicio de Sesión',
      reset_password_title: 'Restablecer su contraseña',
      new_password: 'Nueva Contraseña',
      confirm_password: 'Confirmar Contraseña',
      reset_password: 'Restablecer Contraseña',
      resetting: 'Restableciendo...'
    }
  };

  constructor() {
    const savedLang = localStorage.getItem('lang');
    if (savedLang) {
      this.currentLang = savedLang;
    }
  }

  getCurrentLanguage(): string {
    return this.currentLang;
  }

  setLanguage(lang: string) {
    if (this.translations[lang]) {
      this.currentLang = lang;
      localStorage.setItem('lang', lang);
    }
  }

  // Directly bindable dictionary object in components
  get text(): { [key: string]: string } {
    return this.translations[this.currentLang] || this.translations['en'];
  }
}
